# Generated by Django 4.2 on 2023-05-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebApp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel1',
            new_name='MyMFModel1',
        ),
    ]
