# Generated by Django 4.2 on 2023-05-24 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myWebApp1', '0004_malbum_msong'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymfmodel1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
