# Generated by Django 4.2 on 2023-05-26 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myWebApp1', '0005_mymfmodel1_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymfmodel1',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymfmodel1',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
