# Generated by Django 4.2 on 2023-06-03 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myWebApp1', '0006_mymfmodel1_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAuditLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=200)),
                ('dst', models.CharField(max_length=200)),
                ('action_notes', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.DeleteModel(
            name='clsMFSForm',
        ),
        migrations.RemoveField(
            model_name='msong',
            name='album',
        ),
        migrations.AlterModelOptions(
            name='mymfmodel1',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='mymfmodel1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='mAlbum',
        ),
        migrations.DeleteModel(
            name='mSong',
        ),
    ]
