apiVersion: v1
kind: Secret
metadata:
  name: apisvr-aws-helm-repo
  namespace: default # argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 0**********.dkr.ecr.us-west-1.amazonaws.com/retinalapisvr-chart  
  name: api_helm_oci
  type: helm
  enableOCI: "true"
  password: eyJxxxxxxxxxxxxxxx
  username: XXX
  