apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-gp3-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ebs-sc

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: app-gp3-in-tree
#spec:
#  containers:
#  - name: app
#    image: nginx
#    volumeMounts:
#    - name: persistent-storage
#      mountPath: /usr/share/nginx/html
#  volumes:
#  - name: persistent-storage
#    persistentVolumeClaim:
#      claimName: ebs-gp3-claim