apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: apisvrCluster
  region: us-west-1

managedNodeGroups:
  - name: eks-apisvr-nodegroup
    instanceType: t2.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    spot: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        autoScaler: true

#eksctl create cluster -f init_eks_cluster.yaml
#https://eksctl.io/usage/creating-and-managing-clusters/
#eksctl create cluster --name development --dry-run

#The real maximum number of pods per EKS instance are actually listed in this document.
#https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
#t3.micro max 4# eni
